name: Go Build & Testing

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22.7'

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./... &&
           go test -v ./hnet &&
           go test -v ./common &&
           go test -v ./hscore
